### ISSUE TITLE
Moon phase

### ISSUE THREAD

**Issue by kmaustral** [mubarizahmed/obsidian-weather-moon#1]
Thank you for this. I like to know the moon phase, such as Last Quarter. Is it possible to include this as well as how many days old the moon is?

**Comment by mubarizahmed** [comment]
To clarify, do you mean a text output instead of an emoji ("Last Quarter" instead of "🌗")?

Also, isn't the moon's day the same as the age of the moon? If so, this is output by default and can be accessed using the "%M" placeholder in the output format. Sorry, I am not particularly familiar with lunar terminology.

**Comment by kmaustral** [comment]
The emoji is great. But a text output would be good particularly in
distinguishing between the last and first quarter, for instance, or waning
gibbous versus waning crescent.

**Comment by mubarizahmed** [comment]
I added local output formatting. You can now use the placeholder %n for the moon phase text.

**Comment by kmaustral** [comment]
Thanks but %n doesn't seem to generate anything for me.
